# Configuration commune à tous les microservices

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.uuid}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true
        ttl: 5s
      retry:
        enabled: true
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 2
        retry-on-all-operations: true
        backoff:
          enabled: true
          initial-interval: 1000
          multiplier: 1.2
          max-interval: 5000
    circuit-breaker:
      resilience4j:
        enabled: true

  # Base de données commune
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  # Configuration commune pour les uploads
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Configuration Feign commune
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

# Logging commun
logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    org.hibernate: INFO
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
